### ISSUE TITLE
Step 5.1: Launcher启动器

### ISSUE THREAD

**Issue by mrkingu** [mrkingu/knight_hero_server#14]
# 请求: 实现Launcher一键启动系统

## 需求说明
实现服务编排和一键启动系统，支持Supervisor管理进程，自动配置Nginx。

## 技术要求
- YAML配置文件
- Supervisor进程管理
- Nginx自动配置
- 健康检查

### 1. launcher/config.yaml
```yaml
# 部署配置文件
environment: development

services:
  gateway:
    instances: 2
    start_port: 8000
    workers: 4
    env:
      MAX_CONNECTIONS: 10000
      
  logic:
    instances: 2  
    start_port: 9000
    workers: 4
    
  chat:
    instances: 1
    start_port: 9100
    workers: 2
    
  fight:
    instances: 2
    start_port: 9200
    workers: 2
    
redis:
  mode: single  # single/cluster
  host: localhost
  port: 6379
  
mongodb:
  uri: mongodb://localhost:27017/game
  
nginx:
  workers: 4
  port: 80
```

### 2. launcher/launcher.py
```python
实现功能:
- 读取配置文件
- 生成Supervisor配置
- 生成Nginx配置
- 启动所有服务
- 健康检查
```

### 3. launcher/supervisor_gen.py
```python
实现功能:
- 根据配置生成supervisor配置
- 服务分组管理
- 日志配置
- 自动重启策略
```

### 4. launcher/nginx_gen.py
```python
实现功能:
- 生成upstream配置
- WebSocket支持
- 负载均衡策略
- 健康检查配置
```

### 5. launcher/health_check.py
```python
实现功能:
- HTTP健康检查
- gRPC健康检查
- Redis连接检查
- MongoDB连接检查
```

## Supervisor配置示例
```ini
[group:game_server]
programs=gateway_1,gateway_2,logic_1,logic_2,chat_1,fight_1,fight_2

[program:gateway_1]
command=python -m services.gateway.main --port=8001 --workers=4
directory=/opt/game_server
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/game/gateway_1_err.log
stdout_logfile=/var/log/game/gateway_1_out.log
environment=PYTHONPATH="/opt/game_server",ENV="production"

[program:gateway_2]
command=python -m services.gateway.main --port=8002 --workers=4
# ... 类似配置
```

## Nginx配置示例
```nginx
upstream gateway_cluster {
    least_conn;
    server 127.0.0.1:8001 max_fails=3 fail_timeout=30s;
    server 127.0.0.1:8002 max_fails=3 fail_timeout=30s;
    keepalive 300;
}

server {
    listen 80;
    
    location /ws {
        proxy_pass http://gateway_cluster;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
    
    location /health {
        access_log off;
        return 200 "healthy\n";
    }
}
```

## 启动脚本
```python
class Launcher:
    """服务启动器"""
    
    async def start_all(self):
        """启动所有服务"""
        # 1. 检查环境
        await self._check_environment()
        
        # 2. 生成配置
        self._generate_supervisor_config()
        self._generate_nginx_config()
        
        # 3. 启动基础服务
        await self._start_redis()
        await self._start_mongodb()
        
        # 4. 启动Nginx
        await self._start_nginx()
        
        # 5. 启动游戏服务
        await self._start_game_services()
        
        # 6. 健康检查
        await self._health_check_all()
        
        print("所有服务启动成功!")
```
采用MVC模式 采用清晰的文件结构，每个文件只包含一个类

所有代码必须包含详细的中文注释
使用Type Hints进行类型标注
遵循PEP 8编码规范
每个模块都要有对应的单元测试
使用asyncio实现异步编程
注意内存管理和性能优化
